pipeline:
  identifier: Build_shivi22_jhttp_1703141967612
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: proj1
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1702549707973
        repoName: shivi22/jhttp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
