pipeline:
  identifier: Build_shivi22_jhttp_1703141967612
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: proj1
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1702549707973
        repoName: shivi22/jhttp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_java_app
                  name: Build Java App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      mvn -B package --file pom.xm
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
